### ISSUE TITLE
Implementing Quick Sort Algorithm using Java

### ISSUE THREAD

**Issue by LiQuiD-404** [prathimacode-hub/Hacktoberfest-2022#2]
I will be implementing Quick Sort Algorithm using Java.

I will be working on this issue under Hacktoberfest'22.

**Comment by prathimacode-hub** [comment]
This repository is only a pathway to the projects that's been added as part of Hacktoberfest. You can find the list of projects added in README file. Choose one and go to the project to comment on the issues created. Thank You. @LiQuiD-404
